/* Built-in exercise library.
   Row: [id, name, group, equipment, track, pattern, secondary, cue, how[], avoid[]]
   track: 'wr' weight × reps · 'bw' reps (+ optional added weight) · 'time' duration
   pattern: movement pattern — powers "swap exercise" and alternatives. */
'use strict';

const EXDB = (() => {

  const rows = [
    /* ---------------- Chest ---------------- */
    ['bb-bench', 'Barbell Bench Press', 'chest', 'barbell', 'wr', 'hpush', ['triceps', 'front delts'], 'Shoulder blades pinned, feet planted; bar to mid-chest, press up and slightly back.',
      ['Lie with eyes under the bar; pull shoulder blades back and down onto the bench.', 'Grip just outside shoulder width, feet flat and planted.', 'Lower the bar to mid-chest with elbows ~45–70° from your sides.', 'Press up and slightly back toward your face; keep glutes on the bench.'],
      ['Bouncing the bar off the chest.', 'Flaring elbows to 90° — hard on the shoulders.']],
    ['bb-incline-bench', 'Incline Barbell Bench Press', 'chest', 'barbell', 'wr', 'hpush', ['front delts', 'triceps'], '30–45° bench; bar to upper chest, elbows ~45° from torso.',
      ['Set the bench to 30–45°; shoulder blades pinned as on flat bench.', 'Lower the bar to just below the collarbone.', 'Press up in a slight arc until elbows lock out.'],
      ['Setting the incline so steep it becomes a shoulder press.', 'Letting the lower back leave the bench.']],
    ['db-bench', 'Dumbbell Bench Press', 'chest', 'dumbbell', 'wr', 'hpush', ['triceps', 'front delts'], 'Deep stretch at the bottom, press up and slightly in; don’t clang at the top.',
      ['Kick the bells up as you lie back; start pressed above your chest.', 'Lower with forearms vertical until you feel a full chest stretch.', 'Press up and slightly inward without banging the bells together.'],
      ['Cutting the range short at the bottom — the stretch is where the growth is.']],
    ['db-incline-bench', 'Incline Dumbbell Press', 'chest', 'dumbbell', 'wr', 'hpush', ['front delts', 'triceps'], '30° incline; lower to outer chest with forearms vertical.',
      ['Bench at ~30°; bells start above your upper chest.', 'Lower to the outer chest, elbows ~45° from your sides.', 'Drive both bells up and slightly together.'],
      ['Arching so much the incline becomes flat pressing.']],
    ['bb-decline-bench', 'Decline Bench Press', 'chest', 'barbell', 'wr', 'hpush', ['triceps'], 'Bar to lower chest; short controlled range, no bounce.',
      ['Hook your legs in, shoulder blades set as usual.', 'Lower to the lower chest line under control.', 'Press straight up; the range is shorter than flat bench.'],
      ['Loading it heavier than flat and bouncing the short range.']],
    ['machine-chest-press', 'Machine Chest Press', 'chest', 'machine', 'wr', 'hpush', ['triceps', 'front delts'], 'Handles at mid-chest height; full stretch without shoulders rolling forward.',
      ['Set the seat so handles sit at mid-chest.', 'Press to just short of locked elbows.', 'Return slowly until you feel a chest stretch, shoulders staying back.'],
      ['Letting the shoulders roll forward at the stretch.']],
    ['push-up', 'Push-Up', 'chest', 'bodyweight', 'bw', 'hpush', ['triceps', 'core'], 'Rigid plank line; chest to the floor, elbows ~45°.',
      ['Hands slightly wider than shoulders, body in one rigid line.', 'Lower until your chest nearly touches the floor, elbows ~45° out.', 'Press back up without the hips sagging or piking.'],
      ['Sagging hips.', 'Half reps — chest to the floor or elevate your hands.']],
    ['dip-chest', 'Chest Dip', 'chest', 'bodyweight', 'bw', 'hpush', ['triceps', 'front delts'], 'Lean forward with a slight elbow flare; deep stretch, stop before shoulder pinch.',
      ['Support on parallel bars, lean the torso forward ~20–30°.', 'Lower until you feel a strong chest stretch — stop before the shoulders pinch.', 'Press back up, staying tilted forward.'],
      ['Going deeper than your shoulders allow.', 'Staying bolt upright (that shifts it to triceps).']],
    ['cable-fly', 'Cable Fly', 'chest', 'cable', 'wr', 'iso-chest', ['front delts'], 'Slight elbow bend held constant; hug arc, squeeze at the midline.',
      ['Set cables at chest height, one step forward, slight stagger stance.', 'With a fixed slight elbow bend, sweep your hands together in a hug.', 'Squeeze for a beat at the midline, then open slowly to a stretch.'],
      ['Turning it into a press by bending the elbows more as you tire.']],
    ['cable-fly-low', 'Low-to-High Cable Fly', 'chest', 'cable', 'wr', 'iso-chest', ['front delts'], 'Cables low; sweep up to eye level, upper-chest bias.',
      ['Set cables at the lowest position, palms facing up-and-in.', 'Sweep up and together to eye level.', 'Lower slowly back to the stretched start.'],
      ['Shrugging the shoulders up as you lift.']],
    ['db-fly', 'Dumbbell Fly', 'chest', 'dumbbell', 'wr', 'iso-chest', ['front delts'], 'Wide arc, gentle stretch — go lighter than you think.',
      ['Lie back with bells above your chest, slight elbow bend.', 'Open wide until you feel a comfortable stretch — no deeper.', 'Bring them back together along the same arc.'],
      ['Going heavy — this is a stretch-and-squeeze move, not a press.']],
    ['pec-deck', 'Pec Deck', 'chest', 'machine', 'wr', 'iso-chest', [], 'Elbows just below shoulder height; pause the squeeze for a beat.',
      ['Set the seat so your elbows sit just below shoulder height.', 'Bring the pads together and pause one second.', 'Open slowly to a comfortable stretch.'],
      ['Letting the weight yank you open at the stretch.']],

    /* ---------------- Back ---------------- */
    ['deadlift', 'Deadlift', 'back', 'barbell', 'wr', 'hinge', ['hamstrings', 'glutes', 'traps', 'core'], 'Bar over mid-foot, brace hard, push the floor away; hips and chest rise together.',
      ['Bar over mid-foot; grip just outside your legs.', 'Flatten your back, take the slack out of the bar, big brace.', 'Push the floor away — hips and chest rise at the same rate.', 'Lock out tall by squeezing glutes; don’t lean back.'],
      ['Rounding the lower back under load.', 'Jerking the bar off the floor instead of pushing.']],
    ['trapbar-deadlift', 'Trap Bar Deadlift', 'back', 'barbell', 'wr', 'hinge', ['quads', 'glutes', 'traps'], 'Neutral grip, more upright torso than conventional; drive through the whole foot.',
      ['Stand centred in the bar, grip the handles, chest up.', 'Brace, then drive through the whole foot to stand tall.', 'Lower with control by pushing the hips back.'],
      ['Letting the hips shoot up first.']],
    ['rack-pull', 'Rack Pull', 'back', 'barbell', 'wr', 'hinge', ['traps', 'glutes'], 'Pins around knee height; lock out with glutes, not lower-back hyperextension.',
      ['Set pins at or just below knee height.', 'Hinge to the bar, flat back, brace.', 'Stand tall by driving hips through; squeeze the upper back.'],
      ['Leaning back at lockout.', 'Loading far beyond your deadlift just because the range is short.']],
    ['pull-up', 'Pull-Up', 'back', 'bodyweight', 'bw', 'vpull', ['biceps', 'rear delts'], 'Dead hang to chin over bar; lead with the chest, no kipping.',
      ['Overhand grip just outside shoulders; start from a dead hang.', 'Pull your chest toward the bar, elbows driving down.', 'Chin clears the bar; lower all the way back to a hang.'],
      ['Kipping or cutting the bottom of each rep.', 'Chin-poking at the bar instead of pulling the chest up.']],
    ['chin-up', 'Chin-Up', 'back', 'bodyweight', 'bw', 'vpull', ['biceps'], 'Underhand grip; pull elbows to your ribs, full hang each rep.',
      ['Underhand grip at shoulder width; dead-hang start.', 'Pull elbows down to your ribs until the chin clears.', 'Lower under control to a full hang.'],
      ['Half-range reps that never reach a hang.']],
    ['lat-pulldown', 'Lat Pulldown', 'back', 'cable', 'wr', 'vpull', ['biceps', 'rear delts'], 'Slight lean back; pull the bar to your collarbone, elbows down and in.',
      ['Grip just outside shoulders; thighs snug under the pads.', 'Lean back slightly and pull the bar to your collarbone.', 'Let the bar rise until arms are long and lats stretch.'],
      ['Swinging the torso for momentum.', 'Pulling behind the neck.']],
    ['bb-row', 'Barbell Row', 'back', 'barbell', 'wr', 'hpull', ['lats', 'biceps', 'rear delts'], 'Hinge to ~45°; row to the lower ribs, keep the torso angle fixed.',
      ['Hinge to ~45°, flat back, bar hanging under your shoulders.', 'Row the bar to your lower ribs, elbows staying close.', 'Lower until arms are long without the torso rising.'],
      ['Standing up as you pull — the angle is the exercise.']],
    ['pendlay-row', 'Pendlay Row', 'back', 'barbell', 'wr', 'hpull', ['lats', 'biceps'], 'Torso parallel, bar from a dead stop on the floor each rep; explosive pull.',
      ['Torso parallel to the floor, bar on the ground each rep.', 'Pull explosively to the lower chest.', 'Return the bar to a dead stop; reset your back and repeat.'],
      ['Letting the torso creep upright as the set goes on.']],
    ['db-row', 'One-Arm Dumbbell Row', 'back', 'dumbbell', 'wr', 'hpull', ['lats', 'biceps'], 'Per side. Hand and knee on bench; row to the hip, no torso twist.',
      ['One hand and knee on the bench, back flat.', 'Row the bell toward your hip, elbow skimming your side.', 'Lower long, letting the lat stretch, without twisting the torso.'],
      ['Rotating the torso to heave the weight up.']],
    ['cable-row', 'Seated Cable Row', 'back', 'cable', 'wr', 'hpull', ['lats', 'biceps'], 'Chest tall; pull to the navel, let the shoulder blades glide forward on the return.',
      ['Sit tall, knees soft, chest proud.', 'Pull the handle to your navel, squeezing the blades together.', 'Return slowly, letting the blades glide forward for a stretch.'],
      ['Rowing with your lower back by rocking.']],
    ['tbar-row', 'T-Bar Row', 'back', 'barbell', 'wr', 'hpull', ['lats', 'biceps'], 'Chest up, hips back; squeeze the plates to your chest without heaving.',
      ['Straddle the bar, hinge with a flat back.', 'Pull the handles to your chest, elbows tight.', 'Lower with control to long arms.'],
      ['Heaving with the hips on every rep.']],
    ['cs-row', 'Chest-Supported Row', 'back', 'dumbbell', 'wr', 'hpull', ['lats', 'rear delts'], 'Chest glued to the incline bench — zero momentum, all back.',
      ['Lie chest-down on an incline bench, bells hanging.', 'Row both elbows back and up, chest staying on the pad.', 'Lower slowly to a full hang.'],
      ['Lifting the chest off the pad to cheat the weight up.']],
    ['machine-row', 'Machine Row', 'back', 'machine', 'wr', 'hpull', ['lats', 'biceps'], 'Drive elbows back, pause, slow return; don’t shrug into it.',
      ['Chest against the pad, arms long.', 'Drive the elbows back, pause a beat at the squeeze.', 'Return slowly to a full stretch.'],
      ['Shrugging the shoulders toward the ears as you pull.']],
    ['straight-arm-pd', 'Straight-Arm Pulldown', 'back', 'cable', 'wr', 'vpull', ['lats'], 'Arms nearly straight; sweep the bar to your thighs, feel the lats lengthen up top.',
      ['Face a high cable, slight hinge, arms nearly straight.', 'Sweep the bar down to your thighs in an arc.', 'Let it rise until your lats stretch overhead.'],
      ['Bending the elbows and turning it into a pushdown.']],
    ['inverted-row', 'Inverted Row', 'back', 'bodyweight', 'bw', 'hpull', ['biceps', 'core'], 'Rigid body line under a bar; chest to bar, lower with control.',
      ['Hang under a bar, heels on the floor, body in one line.', 'Pull your chest to the bar, elbows driving back.', 'Lower with control; walk feet closer to make it harder.'],
      ['Hips sagging out of the plank line.']],
    ['back-extension', 'Back Extension', 'back', 'bodyweight', 'bw', 'hinge', ['glutes', 'hamstrings'], 'Hinge at the hips over the pad; rise to a straight line, not hyperextension.',
      ['Set the pad at the hip crease; fold over it.', 'Rise by squeezing glutes and hamstrings until the body is straight.', 'Lower under control; add weight by hugging a plate.'],
      ['Arching past straight at the top.']],
    ['bb-shrug', 'Barbell Shrug', 'back', 'barbell', 'wr', 'grip', ['traps'], 'Straight up and down, pause at the top; no rolling.',
      ['Hold the bar at arm’s length, stand tall.', 'Shrug the shoulders straight up toward your ears; pause.', 'Lower fully — the stretch matters.'],
      ['Rolling the shoulders in circles.']],

    /* ---------------- Shoulders ---------------- */
    ['ohp', 'Overhead Press', 'shoulders', 'barbell', 'wr', 'vpush', ['triceps', 'upper chest', 'core'], 'Squeeze glutes, ribs down; press to lockout with the bar over mid-foot.',
      ['Bar at the front of the shoulders, elbows slightly forward.', 'Squeeze glutes, brace, then press as the head moves back slightly.', 'Finish with the bar over mid-foot, arms locked, shrug the top.'],
      ['Leaning way back and turning it into an incline press.', 'Pressing around the chin instead of moving the head back.']],
    ['db-shoulder-press', 'Seated Dumbbell Shoulder Press', 'shoulders', 'dumbbell', 'wr', 'vpush', ['triceps'], 'Start at ear height; press up and slightly in, don’t arch off the pad.',
      ['Sit with back supported; bells at ear height, palms forward.', 'Press up and slightly in until arms are long.', 'Lower with control back to ear height.'],
      ['Arching off the backrest to grind out reps.']],
    ['arnold-press', 'Arnold Press', 'shoulders', 'dumbbell', 'wr', 'vpush', ['triceps'], 'Rotate palms from facing you to facing forward as you press.',
      ['Start with bells at shoulder height, palms facing you.', 'Rotate the palms outward as you press overhead.', 'Reverse the rotation on the way down.'],
      ['Rushing the rotation — it should be smooth, not a flick.']],
    ['machine-shoulder-press', 'Machine Shoulder Press', 'shoulders', 'machine', 'wr', 'vpush', ['triceps'], 'Grips level with ears; smooth press, no locking out hard.',
      ['Adjust the seat so the handles start level with your ears.', 'Press to just short of hard lockout.', 'Lower slowly to the start.'],
      ['Half reps at the top of the stack.']],
    ['lateral-raise', 'Dumbbell Lateral Raise', 'shoulders', 'dumbbell', 'wr', 'iso-side', [], 'Lead with the elbows to shoulder height; tip the pinky slightly up, drift arms a touch forward.',
      ['Stand tall, bells at your sides, slight elbow bend.', 'Raise out and slightly forward, leading with the elbows.', 'Stop at shoulder height; lower twice as slowly.'],
      ['Swinging from the hips.', 'Shrugging the traps into the lift.']],
    ['cable-lateral-raise', 'Cable Lateral Raise', 'shoulders', 'cable', 'wr', 'iso-side', [], 'Per side. Cable behind the body; constant tension through the whole arc.',
      ['Cable at the lowest setting, handle in the far hand, behind your body.', 'Raise out to shoulder height, elbow leading.', 'Lower slowly — the cable keeps tension the whole way.'],
      ['Standing so close the cable goes slack at the bottom.']],
    ['front-raise', 'Front Raise', 'shoulders', 'dumbbell', 'wr', 'iso-side', [], 'To eye level, one count down; no swinging from the hips.',
      ['Bells resting on your thighs, palms down.', 'Raise one or both to eye level with straight-ish arms.', 'Lower under control; alternate if that keeps you stricter.'],
      ['Rocking the torso to start each rep.']],
    ['rear-delt-fly', 'Rear Delt Fly', 'shoulders', 'dumbbell', 'wr', 'iso-rear', ['upper back'], 'Hinge over; sweep wide with soft elbows, thumbs slightly down.',
      ['Hinge until your torso is near parallel, bells hanging.', 'Sweep wide with soft elbows, thumbs tipped slightly down.', 'Pause briefly at the top; lower slowly.'],
      ['Turning it into a row by bending the elbows.']],
    ['reverse-pec-deck', 'Reverse Pec Deck', 'shoulders', 'machine', 'wr', 'iso-rear', ['upper back'], 'Arms just below shoulder height; open wide, pause, resist the return.',
      ['Face the pad; set handles so your arms are just below shoulder height.', 'Open wide until your arms are in line with your shoulders.', 'Pause, then resist the return.'],
      ['Pulling with bent elbows and rowing it.']],
    ['face-pull', 'Face Pull', 'shoulders', 'cable', 'wr', 'iso-rear', ['rear delts', 'traps'], 'Rope to the bridge of your nose; finish with knuckles back, elbows high.',
      ['Rope at upper-chest height; grab with thumbs toward you.', 'Pull toward the bridge of your nose, elbows high and wide.', 'Finish with knuckles beside your ears; return slowly.'],
      ['Loading it so heavy it becomes a low row.']],
    ['upright-row', 'Upright Row', 'shoulders', 'barbell', 'wr', 'iso-side', ['traps'], 'Wide-ish grip to lower-chest height; stop if the shoulders complain.',
      ['Take a grip a bit wider than shoulders.', 'Pull the bar up your body to lower-chest height, elbows leading.', 'Lower slowly; keep the range comfortable for your shoulders.'],
      ['Pulling to chin height with a narrow grip — a common impingement recipe.']],
    ['landmine-press', 'Landmine Press', 'shoulders', 'barbell', 'wr', 'vpush', ['upper chest', 'triceps', 'core'], 'Per side. Half-kneeling; press up and forward along the bar’s arc.',
      ['Half-kneel with the bar end at your shoulder.', 'Press up and forward along the bar’s natural arc.', 'Lower to the shoulder with control; brace so the torso stays tall.'],
      ['Twisting the torso as you press.']],

    /* ---------------- Biceps ---------------- */
    ['bb-curl', 'Barbell Curl', 'biceps', 'barbell', 'wr', 'iso-bi', ['forearms'], 'Elbows pinned to your sides; full extension at the bottom, no hip swing.',
      ['Stand tall, grip at shoulder width, arms long.', 'Curl the bar up with elbows pinned to your sides.', 'Lower all the way to straight arms each rep.'],
      ['Swinging the hips to start the rep.', 'Elbows drifting forward at the top.']],
    ['ez-curl', 'EZ-Bar Curl', 'biceps', 'barbell', 'wr', 'iso-bi', ['forearms'], 'Angled grip is easier on wrists; control the negative.',
      ['Grip the angled sections, arms long at your sides.', 'Curl to shoulder height, elbows pinned.', 'Take 2–3 seconds on the way down.'],
      ['Cutting the bottom half of the rep.']],
    ['db-curl', 'Dumbbell Curl', 'biceps', 'dumbbell', 'wr', 'iso-bi', ['forearms'], 'Supinate as you lift — pinky toward the ceiling at the top.',
      ['Bells at your sides, palms in.', 'Curl and rotate so palms face up, pinky twisting toward the ceiling.', 'Lower with the same rotation in reverse.'],
      ['Rocking the shoulders to lift heavier bells than your biceps can curl.']],
    ['hammer-curl', 'Hammer Curl', 'biceps', 'dumbbell', 'wr', 'iso-bi', ['brachialis', 'forearms'], 'Neutral grip throughout; strict elbows, slow lowering.',
      ['Neutral (thumbs-up) grip, arms long.', 'Curl to shoulder height without rotating.', 'Lower slowly to full extension.'],
      ['Swinging both bells with body English.']],
    ['incline-curl', 'Incline Dumbbell Curl', 'biceps', 'dumbbell', 'wr', 'iso-bi', [], '45–60° bench, arms hanging behind you; big stretch at the bottom.',
      ['Lie back on a 45–60° bench, arms hanging straight down.', 'Curl without letting the elbows drift forward.', 'Lower to a full stretch behind your body line.'],
      ['Letting the elbows swing forward, killing the stretch.']],
    ['preacher-curl', 'Preacher Curl', 'biceps', 'machine', 'wr', 'iso-bi', [], 'Armpits over the pad; stop just short of full lockout at the bottom under load.',
      ['Armpits snug over the pad, arms on the slope.', 'Curl up smoothly; squeeze at the top.', 'Lower slowly, stopping just before brutal full extension.'],
      ['Slamming into full extension with heavy weight — rough on the tendon.']],
    ['cable-curl', 'Cable Curl', 'biceps', 'cable', 'wr', 'iso-bi', ['forearms'], 'Constant tension; step back a touch so there’s load at full extension.',
      ['Low cable, step back so the cable is taut at arms-long.', 'Curl with pinned elbows.', 'Lower to full extension against the constant pull.'],
      ['Standing on top of the pulley so the bottom is slack.']],
    ['concentration-curl', 'Concentration Curl', 'biceps', 'dumbbell', 'wr', 'iso-bi', [], 'Per side. Elbow braced on inner thigh; slow squeeze, no shoulder drift.',
      ['Seated, elbow braced against your inner thigh.', 'Curl slowly to your shoulder; squeeze hard at the top.', 'Lower over 2–3 seconds to a straight arm.'],
      ['Leaning back to finish reps.']],
    ['spider-curl', 'Spider Curl', 'biceps', 'dumbbell', 'wr', 'iso-bi', [], 'Chest on an incline bench, arms vertical; strict short arc.',
      ['Chest down on an incline bench, arms hanging vertical.', 'Curl up without the upper arms moving.', 'Lower fully — gravity keeps you honest here.'],
      ['Swinging the upper arms to shorten the movement.']],

    /* ---------------- Triceps ---------------- */
    ['cg-bench', 'Close-Grip Bench Press', 'triceps', 'barbell', 'wr', 'hpush', ['chest', 'front delts'], 'Hands just inside shoulder width; elbows tucked, bar to lower chest.',
      ['Grip just inside shoulder width — not thumbs-touching.', 'Lower to the lower chest with elbows tucked close.', 'Press up, finishing with a hard triceps lockout.'],
      ['Gripping so narrow the wrists hurt.']],
    ['skull-crusher', 'Skull Crusher', 'triceps', 'barbell', 'wr', 'iso-tri', [], 'Lower to the forehead or just behind; elbows still, forearms do the work.',
      ['Lie back, bar pressed above your face, elbows in.', 'Bend only the elbows, lowering to the forehead or just behind.', 'Extend back to lockout without flaring.'],
      ['Elbows drifting apart under fatigue.', 'Bouncing at the bottom.']],
    ['pushdown', 'Cable Pushdown', 'triceps', 'cable', 'wr', 'iso-tri', [], 'Elbows pinned; press to full lockout, let the bar rise only to chest height.',
      ['High cable, elbows pinned to your sides.', 'Press down to full lockout; squeeze.', 'Let the bar rise only to chest height before the next rep.'],
      ['Leaning over the bar and pressing with bodyweight.']],
    ['rope-oh-ext', 'Overhead Rope Extension', 'triceps', 'cable', 'wr', 'iso-tri', [], 'Face away, arms overhead; deep stretch behind the head, extend fully.',
      ['Face away from a low cable, rope behind your head.', 'Let the rope stretch the triceps deep behind you.', 'Extend overhead, splitting the rope at the top.'],
      ['Elbows flaring wide instead of pointing forward.']],
    ['db-oh-ext', 'Dumbbell Overhead Extension', 'triceps', 'dumbbell', 'wr', 'iso-tri', [], 'Both hands under one bell; elbows close to your ears.',
      ['Hold one bell overhead, both palms under the top plate.', 'Lower behind your head until the triceps stretch fully.', 'Extend back up, elbows staying close to your ears.'],
      ['Turning it into a press by moving the upper arms.']],
    ['dip-triceps', 'Triceps Dip', 'triceps', 'bodyweight', 'bw', 'iso-tri', ['chest', 'front delts'], 'Upright torso, elbows tracking back; full lockout at the top.',
      ['On parallel bars, torso as upright as you can keep it.', 'Lower until the upper arms are about parallel.', 'Press to a full lockout.'],
      ['Diving deep with shoulders rolled forward.']],
    ['bench-dip', 'Bench Dip', 'triceps', 'bodyweight', 'bw', 'iso-tri', ['front delts'], 'Hands on a bench behind you; hips close to the bench, shallow if shoulders niggle.',
      ['Hands on the bench edge behind you, legs out front.', 'Lower until the upper arms are near parallel — no deeper.', 'Press back to straight arms, hips staying close to the bench.'],
      ['Sinking so deep the front of the shoulder complains.']],
    ['kickback', 'Triceps Kickback', 'triceps', 'dumbbell', 'wr', 'iso-tri', [], 'Per side. Upper arm parallel to the floor and frozen; snap to lockout, pause.',
      ['Hinge over, upper arm locked parallel to the floor.', 'Extend to a straight arm; pause one beat.', 'Lower only the forearm back down.'],
      ['Dropping the elbow and swinging the whole arm.']],

    /* ---------------- Forearms & grip ---------------- */
    ['wrist-curl', 'Wrist Curl', 'forearms', 'dumbbell', 'wr', 'grip', [], 'Forearms on a bench, palms up; curl through a full wrist range.',
      ['Forearms resting on a bench, wrists just off the edge, palms up.', 'Let the weight roll toward the fingers, then curl the wrists up.', 'Move slowly through the full range.'],
      ['Using the arms instead of just the wrists.']],
    ['rev-wrist-curl', 'Reverse Wrist Curl', 'forearms', 'dumbbell', 'wr', 'grip', [], 'Palms down; lighter than wrist curls — extensors are small.',
      ['Forearms on a bench, palms down.', 'Lift the knuckles up as far as they go.', 'Lower slowly; expect to use very light weight.'],
      ['Loading it like a wrist curl — the extensors are much weaker.']],
    ['reverse-curl', 'Reverse Curl', 'forearms', 'barbell', 'wr', 'iso-bi', ['biceps', 'brachialis'], 'Overhand grip; strict elbows, wrists straight.',
      ['Overhand grip at shoulder width.', 'Curl with pinned elbows, wrists held straight.', 'Lower slowly to full extension.'],
      ['Letting the wrists collapse backward.']],
    ['dead-hang', 'Dead Hang', 'forearms', 'bodyweight', 'time', 'grip', ['lats', 'shoulders'], 'Full grip on the bar, shoulders active-ish; breathe and hang.',
      ['Grip the bar with your whole hand, not fingertips.', 'Hang with shoulders neither fully shrugged nor slack.', 'Breathe steadily and accumulate time.'],
      ['Death-gripping so hard you hold your breath.']],
    ['farmers-carry', 'Farmer’s Carry', 'forearms', 'dumbbell', 'time', 'grip', ['traps', 'core', 'grip'], 'Heavy in each hand; tall posture, quick small steps.',
      ['Pick up a heavy bell in each hand with a deadlift, not a bend.', 'Walk tall with quick, small steps.', 'Set them down with a flat back when the grip goes.'],
      ['Letting the shoulders slump forward as you fatigue.']],

    /* ---------------- Quads ---------------- */
    ['back-squat', 'Back Squat', 'quads', 'barbell', 'wr', 'squat', ['glutes', 'core', 'hamstrings'], 'Brace, sit down between your heels; drive up through mid-foot, chest proud.',
      ['Bar on the upper back, hands squeezing it in tight.', 'Big breath and brace, then sit down between your heels.', 'Hit at least parallel, knees tracking over the toes.', 'Drive up through mid-foot, chest rising with the hips.'],
      ['Knees caving inward on the way up.', 'Chest collapsing so it becomes a good morning.']],
    ['front-squat', 'Front Squat', 'quads', 'barbell', 'wr', 'squat', ['glutes', 'core', 'upper back'], 'Elbows high, upright torso; the rack position is the exercise.',
      ['Bar on the front of the shoulders, elbows driven high.', 'Squat down keeping the torso as upright as possible.', 'Drive up, elbows staying high the whole way.'],
      ['Elbows dropping — the bar rolls forward and the set is over.']],
    ['goblet-squat', 'Goblet Squat', 'quads', 'dumbbell', 'wr', 'squat', ['glutes', 'core'], 'Bell at your chest; elbows inside knees at depth, heels down.',
      ['Hold a bell vertically against your chest.', 'Squat until your elbows brush the inside of your knees.', 'Stand by pushing the floor away, heels down throughout.'],
      ['Letting the bell drift away from the chest.']],
    ['box-squat', 'Box Squat', 'quads', 'barbell', 'wr', 'squat', ['glutes'], 'Sit back to a box, brief pause, no rocking; stand aggressively.',
      ['Set a box at or just below parallel behind you.', 'Sit back until you touch down softly; pause without relaxing.', 'Stand aggressively without rocking forward.'],
      ['Plopping onto the box and rocking to stand.']],
    ['leg-press', 'Leg Press', 'quads', 'machine', 'wr', 'squat', ['glutes'], 'Feet mid-platform; lower until hips begin to curl, never slam lockout.',
      ['Feet mid-platform, about hip width.', 'Lower until just before your hips curl off the pad.', 'Press through the whole foot to just short of locked knees.'],
      ['Slamming into knee lockout.', 'Going so deep the lower back rounds off the seat.']],
    ['hack-squat', 'Hack Squat', 'quads', 'machine', 'wr', 'squat', ['glutes'], 'Back flat on the pad; deep knee bend, drive evenly through both feet.',
      ['Back and hips flat against the pads, feet mid-platform.', 'Lower deep, knees tracking over toes.', 'Drive up evenly through both feet.'],
      ['Half reps with a stack of plates.']],
    ['bss', 'Bulgarian Split Squat', 'quads', 'dumbbell', 'wr', 'lunge', ['glutes'], 'Per side. Rear foot on a bench; drop the back knee straight down, front heel loaded.',
      ['Rear foot laces-down on a bench, front foot well forward.', 'Drop the back knee straight down toward the floor.', 'Drive up through the front heel; complete all reps, then switch.'],
      ['Front knee shooting far past the toes with the heel lifting.', 'Bouncing off the back leg.']],
    ['walking-lunge', 'Walking Lunge', 'quads', 'dumbbell', 'wr', 'lunge', ['glutes'], 'Long stride, torso tall; knee tracks over toes, push off the front leg.',
      ['Step forward long, torso tall.', 'Lower until the back knee kisses the floor.', 'Push off the front leg into the next stride.'],
      ['Short choppy steps that stay on the toes.']],
    ['reverse-lunge', 'Reverse Lunge', 'quads', 'dumbbell', 'wr', 'lunge', ['glutes'], 'Per side. Step back, drop the knee; easier on the knees than forward lunges.',
      ['Step backward into a long stance.', 'Lower the back knee to just above the floor.', 'Drive through the front heel to stand; alternate or complete a side.'],
      ['Leaning forward and pushing off the back toes.']],
    ['step-up', 'Step-Up', 'quads', 'dumbbell', 'wr', 'lunge', ['glutes'], 'Per side. Box at knee height; drive through the top foot only — no bounce off the floor.',
      ['Box around knee height; whole foot on top.', 'Drive through the top leg only until you stand tall on the box.', 'Lower slowly with the same leg doing the work.'],
      ['Bouncing off the bottom foot — it steals the whole exercise.']],
    ['leg-extension', 'Leg Extension', 'quads', 'machine', 'wr', 'iso-quad', [], 'Pause a beat at full extension; lower slowly, don’t let the stack crash.',
      ['Pad on the front of the ankles, back against the seat.', 'Extend to straight knees; pause one beat.', 'Lower slowly without the stack touching down.'],
      ['Kicking the weight up with momentum.']],
    ['sissy-squat', 'Sissy Squat', 'quads', 'bodyweight', 'bw', 'iso-quad', [], 'Heels up, knees travel far forward, body leans back in one line. Advanced.',
      ['Heels raised, hold something for balance.', 'Let the knees travel far forward as the body leans back in one line.', 'Lower as far as comfortable, then squeeze the quads to return.'],
      ['Hinging at the hips — the line from knee to head stays straight.']],

    /* ---------------- Hamstrings ---------------- */
    ['rdl', 'Romanian Deadlift', 'hamstrings', 'barbell', 'wr', 'hinge', ['glutes', 'lower back'], 'Soft knees, push hips back until hamstrings pull; bar glued to your legs.',
      ['Start standing, bar in hands, knees soft.', 'Push the hips straight back, bar sliding down the thighs.', 'Stop when the hamstrings pull hard (usually mid-shin).', 'Drive the hips forward to stand, squeezing glutes.'],
      ['Bending the knees into a squat.', 'Letting the bar drift away from the legs.']],
    ['sldl', 'Stiff-Leg Deadlift', 'hamstrings', 'barbell', 'wr', 'hinge', ['glutes', 'lower back'], 'Straighter knees than RDL, from the floor; only as deep as a flat back allows.',
      ['Set up like a deadlift with only a slight knee bend.', 'Hinge down keeping the back flat, bar close.', 'Go only as deep as your flat back allows; stand tall.'],
      ['Rounding the back to reach the floor.']],
    ['lying-leg-curl', 'Lying Leg Curl', 'hamstrings', 'machine', 'wr', 'iso-ham', ['calves'], 'Hips pressed into the pad; curl to full contraction, 3-count lowering.',
      ['Lie face down, pad just above the heels.', 'Curl to full contraction without the hips lifting.', 'Lower over three seconds to long legs.'],
      ['Hips popping up to cheat the curl.']],
    ['seated-leg-curl', 'Seated Leg Curl', 'hamstrings', 'machine', 'wr', 'iso-ham', [], 'Thigh pad snug; long-length stretch makes this one count.',
      ['Thigh pad clamped snug, legs long.', 'Curl down and under as far as the machine allows.', 'Return slowly to the stretched start — that stretch is the magic.'],
      ['Sliding forward in the seat to shorten the range.']],
    ['nordic-curl', 'Nordic Curl', 'hamstrings', 'bodyweight', 'bw', 'iso-ham', [], 'Ankles anchored; lower as slowly as possible, push back up. Brutal — few reps is fine.',
      ['Kneel with ankles anchored firmly.', 'Keeping hips straight, lower your body forward as slowly as possible.', 'Catch yourself with your hands; push back up as needed.'],
      ['Breaking at the hips — keep knee-to-shoulder in one line.']],
    ['good-morning', 'Good Morning', 'hamstrings', 'barbell', 'wr', 'hinge', ['glutes', 'lower back'], 'Light bar, big hip hinge; torso to ~45°, flat back throughout.',
      ['Light bar on the upper back, knees soft.', 'Hinge the hips back until the torso reaches ~45°.', 'Stand by driving the hips forward.'],
      ['Going heavy — this rewards patience, not loading.']],
    ['sl-rdl', 'Single-Leg RDL', 'hamstrings', 'dumbbell', 'wr', 'hinge', ['glutes', 'balance'], 'Per side. Hips square, back leg reaches long; a runner’s best friend.',
      ['Stand on one leg, bell in the opposite hand.', 'Hinge forward as the free leg reaches long behind you.', 'Keep the hips square; return by driving the standing hip forward.'],
      ['Opening the hips sideways to fake the balance.']],

    /* ---------------- Glutes ---------------- */
    ['hip-thrust', 'Barbell Hip Thrust', 'glutes', 'barbell', 'wr', 'hinge', ['hamstrings'], 'Upper back on a bench, chin tucked; squeeze to a full hip lockout, ribs down.',
      ['Upper back on a bench, bar (padded) over the hip crease.', 'Feet so shins are vertical at the top.', 'Drive through the heels to a full hip lockout; chin tucked.', 'Pause and squeeze; lower with control.'],
      ['Arching the lower back instead of finishing with the glutes.']],
    ['glute-bridge', 'Glute Bridge', 'glutes', 'bodyweight', 'bw', 'hinge', ['hamstrings'], 'From the floor; posterior-tilt the pelvis, squeeze hard at the top.',
      ['Lie on your back, heels close to your glutes.', 'Tilt the pelvis, then squeeze the glutes to lift the hips.', 'Pause at the top; lower slowly.'],
      ['Pushing through the toes instead of the heels.']],
    ['sumo-deadlift', 'Sumo Deadlift', 'glutes', 'barbell', 'wr', 'hinge', ['hamstrings', 'quads', 'back'], 'Wide stance, toes out; wedge hips down, spread the floor apart.',
      ['Wide stance, toes out ~30°, grip inside the knees.', 'Wedge the hips down and chest up; take the slack out.', 'Spread the floor apart as you drive to lockout.'],
      ['Hips shooting up before the bar leaves the floor.']],
    ['pull-through', 'Cable Pull-Through', 'glutes', 'cable', 'wr', 'hinge', ['hamstrings'], 'Face away, rope between legs; hinge, then snap hips forward to stand.',
      ['Face away from a low cable, rope between your legs.', 'Hinge back until the hamstrings load.', 'Snap the hips forward to stand tall; squeeze.'],
      ['Squatting it instead of hinging.']],
    ['glute-kickback', 'Cable Glute Kickback', 'glutes', 'cable', 'wr', 'iso-glute', [], 'Per side. Kick back and slightly up; squeeze without arching the lower back.',
      ['Cuff on the ankle, hinge slightly and hold the frame.', 'Kick back and slightly up with a straight-ish leg.', 'Squeeze at the top without arching the back; return slowly.'],
      ['Arching the lower back to fake range.']],
    ['hip-abduction', 'Hip Abduction Machine', 'glutes', 'machine', 'wr', 'iso-glute', [], 'Lean slightly forward for upper glute; pause at the widest point.',
      ['Sit with pads outside the knees.', 'Press the knees apart as far as they go; pause.', 'Return slowly without the stack crashing.'],
      ['Rushing reps with a bouncing stack.']],
    ['hip-adduction', 'Hip Adduction Machine', 'glutes', 'machine', 'wr', 'iso-glute', ['adductors'], 'Controlled squeeze in, slow release; big range beats big load.',
      ['Sit with pads inside the knees, legs open to a comfortable stretch.', 'Squeeze the legs together under control.', 'Release slowly back to the stretch.'],
      ['Setting the range wider than your groin is ready for.']],

    /* ---------------- Calves & lower leg ---------------- */
    ['standing-calf-raise', 'Standing Calf Raise', 'calves', 'machine', 'wr', 'calf', [], 'Full stretch at the bottom, 2s pause; rise to tip-toe, no bouncing.',
      ['Balls of the feet on the edge, heels hanging.', 'Sink into a deep stretch and pause two seconds.', 'Rise to full tip-toe; squeeze at the top.'],
      ['Bouncing out of the stretch — the tendon does the work, not the muscle.']],
    ['seated-calf-raise', 'Seated Calf Raise', 'calves', 'machine', 'wr', 'calf', ['soleus'], 'Bent knee hits the soleus — key muscle for runners; slow reps.',
      ['Knees under the pad, balls of feet on the platform.', 'Lower to a deep stretch; pause.', 'Rise slowly to full height — the bent knee targets the soleus.'],
      ['Rushing — the soleus responds to slow, strict work.']],
    ['sl-calf-raise', 'Single-Leg Calf Raise', 'calves', 'bodyweight', 'bw', 'calf', [], 'Per side. On a step, deep stretch; a benchmark of run-ready calves.',
      ['Stand on one foot on a step, heel hanging.', 'Lower to a deep stretch, then rise to full tip-toe.', 'Use fingertips on a wall for balance only.'],
      ['Bending the knee to cheat the rise.']],
    ['tibialis-raise', 'Tibialis Raise', 'calves', 'bodyweight', 'bw', 'calf', ['shins'], 'Back against a wall, heels out; lift toes toward shins. Shin-splint armour.',
      ['Lean your back against a wall, feet a foot-length out.', 'Lift both forefeet toward your shins as high as they go.', 'Lower slowly; high reps work well.'],
      ['Standing so close to the wall there’s no range.']],

    /* ---------------- Core ---------------- */
    ['plank', 'Plank', 'core', 'bodyweight', 'time', 'core-anti', ['shoulders', 'glutes'], 'Forearms down, squeeze glutes, ribs tucked — a straight line, not a sag.',
      ['Forearms down, elbows under shoulders.', 'Squeeze glutes and tuck the ribs — one straight line.', 'Breathe steadily; stop when the line breaks.'],
      ['Hips sagging or piking to survive longer.']],
    ['side-plank', 'Side Plank', 'core', 'bodyweight', 'time', 'core-anti', ['obliques', 'hip stabilisers'], 'Per side. Stack feet, lift hips high; key for runners’ hip stability.',
      ['Elbow under shoulder, feet stacked.', 'Lift the hips until head-to-heels is one line.', 'Hold tall; don’t let the hips dip.'],
      ['Rolling the top shoulder forward.']],
    ['copenhagen-plank', 'Copenhagen Plank', 'core', 'bodyweight', 'time', 'core-anti', ['adductors'], 'Per side. Top foot on a bench, hips lifted; adductor strength = groin insurance.',
      ['Side-plank position with the top foot on a bench.', 'Lift the hips so the body forms one line, bottom leg floating.', 'Bend the top knee on the bench to make it easier.'],
      ['Starting with the full-length version before you’re ready.']],
    ['hanging-knee-raise', 'Hanging Knee Raise', 'core', 'bodyweight', 'bw', 'core-flex', ['hip flexors', 'grip'], 'Curl the pelvis, knees to chest; no swinging between reps.',
      ['Hang from a bar, body still.', 'Curl the pelvis under as you lift knees to chest.', 'Lower slowly and kill the swing before the next rep.'],
      ['Swinging into momentum reps.']],
    ['hanging-leg-raise', 'Hanging Leg Raise', 'core', 'bodyweight', 'bw', 'core-flex', ['hip flexors', 'grip'], 'Straight legs to horizontal or above; slow lowering is the hard part.',
      ['Hang with straight legs.', 'Raise them to horizontal or higher by curling the pelvis.', 'Lower over 2–3 seconds without swinging.'],
      ['Bent-knee kips sold as leg raises.']],
    ['cable-crunch', 'Cable Crunch', 'core', 'cable', 'wr', 'core-flex', [], 'Kneel, rope by your ears; crunch ribs to pelvis, hips still.',
      ['Kneel below a high cable, rope held by your ears.', 'Crunch ribs toward pelvis — the hips don’t move.', 'Return until the abs stretch, not until you sit up.'],
      ['Bowing from the hips with a rigid spine.']],
    ['ab-wheel', 'Ab Wheel Rollout', 'core', 'other', 'bw', 'core-anti', ['lats', 'shoulders'], 'From knees; roll out only as far as you can keep the lower back flat.',
      ['Kneel with the wheel under your shoulders.', 'Roll forward, hips moving with the shoulders as one unit.', 'Go only as far as the lower back stays flat; pull back with abs and lats.'],
      ['Letting the lower back arch at the far point.']],
    ['crunch', 'Crunch', 'core', 'bodyweight', 'bw', 'core-flex', [], 'Short range, chin off chest; exhale as ribs pull down.',
      ['Lie back, knees bent, hands light behind the head.', 'Exhale and curl the ribs toward the pelvis.', 'Lower slowly; the range is short by design.'],
      ['Yanking the neck with your hands.']],
    ['reverse-crunch', 'Reverse Crunch', 'core', 'bodyweight', 'bw', 'core-flex', [], 'Knees to chest, peel the hips off the floor; lower one vertebra at a time.',
      ['Lie back, knees bent over hips.', 'Curl the knees to your chest, peeling hips off the floor.', 'Lower the spine down one vertebra at a time.'],
      ['Swinging the legs and letting momentum lift the hips.']],
    ['situp', 'Sit-Up', 'core', 'bodyweight', 'bw', 'core-flex', ['hip flexors'], 'Full range up; anchor feet only if you must.',
      ['Lie back, knees bent, arms across the chest.', 'Curl up through the spine to sitting.', 'Roll back down under control.'],
      ['Bouncing off the floor between reps.']],
    ['russian-twist', 'Russian Twist', 'core', 'bodyweight', 'bw', 'core-flex', ['obliques'], 'Lean back 45°, rotate shoulder to shoulder; add weight when 20+ is easy.',
      ['Sit, lean back ~45°, heels light or lifted.', 'Rotate the shoulders side to side — the chest turns, not just the arms.', 'Add a weight to your hands once 20+ reps feels easy.'],
      ['Flapping the arms across while the torso stays still.']],
    ['dead-bug', 'Dead Bug', 'core', 'bodyweight', 'bw', 'core-anti', [], 'Lower back welded to the floor; opposite arm and leg reach long, slow.',
      ['On your back, arms up, knees over hips.', 'Press the lower back into the floor and keep it there.', 'Reach opposite arm and leg long; return slowly and switch.'],
      ['The lower back peeling off the floor as the leg lowers.']],
    ['bird-dog', 'Bird Dog', 'core', 'bodyweight', 'bw', 'core-anti', ['glutes', 'lower back'], 'Per side. From all fours, reach long not high; hips stay level.',
      ['On all fours, back flat.', 'Reach one arm and the opposite leg long — not high.', 'Pause, return without the hips tipping, switch sides.'],
      ['Lifting the leg so high the back arches.']],
    ['pallof-press', 'Pallof Press', 'core', 'cable', 'wr', 'core-anti', ['obliques'], 'Per side. Press the handle straight out and resist the twist; anti-rotation gold.',
      ['Stand side-on to a cable at chest height, handle at your sternum.', 'Press straight out and hold — the cable tries to twist you.', 'Resist, return, and breathe; switch sides.'],
      ['Letting the shoulders rotate toward the machine.']],
    ['v-up', 'V-Up', 'core', 'bodyweight', 'bw', 'core-flex', ['hip flexors'], 'Fold in half, fingers to toes; keep the lower back honest.',
      ['Lie flat, arms overhead.', 'Fold up in one piece, fingers reaching for toes.', 'Lower both halves slowly back to flat.'],
      ['Throwing the arms for momentum.']],
    ['mountain-climbers', 'Mountain Climbers', 'core', 'bodyweight', 'time', 'core-flex', ['shoulders', 'cardio'], 'Plank position; drive knees fast without bouncing the hips.',
      ['Strong plank on the hands.', 'Drive the knees toward the chest alternately, fast.', 'Hips stay level — the legs move, the trunk doesn’t.'],
      ['Hips bouncing skyward as you speed up.']],

    /* ---------------- Full body & power ---------------- */
    ['kb-swing', 'Kettlebell Swing', 'full', 'kettlebell', 'wr', 'power', ['glutes', 'hamstrings', 'core'], 'A hip hinge, not a squat; snap the hips, bell floats to chest height.',
      ['Bell on the floor a foot ahead; hike it back like a snap.', 'Snap the hips forward — the bell floats to chest height.', 'Let it swing back through the legs into the next rep.'],
      ['Squatting and front-raising the bell with the arms.']],
    ['power-clean', 'Power Clean', 'full', 'barbell', 'wr', 'power', ['traps', 'glutes', 'quads'], 'Explosive triple extension; catch high in a quarter squat. Technique first.',
      ['Deadlift start, bar close.', 'Explode through hips-knees-ankles, shrugging the bar up.', 'Catch on the front of the shoulders in a quarter squat, elbows whipping through.'],
      ['Curling the bar up with the arms.', 'Adding load before the catch is clean.']],
    ['push-press', 'Push Press', 'full', 'barbell', 'wr', 'power', ['shoulders', 'triceps', 'quads'], 'Shallow knee dip, drive through the legs into a fast lockout.',
      ['Bar racked on the shoulders as for a press.', 'Dip a few inches with a vertical torso.', 'Drive up hard with the legs and punch the bar to lockout.'],
      ['A deep, slow dip that kills the bounce.']],
    ['thruster', 'Thruster', 'full', 'barbell', 'wr', 'power', ['quads', 'shoulders'], 'Front squat straight into a press — one fluid movement.',
      ['Front squat down with the bar racked.', 'Drive up and let the momentum flow straight into a press.', 'Lock out overhead; lower and repeat as one movement.'],
      ['Pausing between the squat and the press.']],
    ['turkish-getup', 'Turkish Get-Up', 'full', 'kettlebell', 'wr', 'power', ['shoulders', 'core'], 'Per side. Slow and deliberate through each position; eyes on the bell.',
      ['Lie down, bell pressed above you, eyes on it.', 'Roll to the elbow, then the hand; sweep the leg through to kneel.', 'Stand tall, then reverse every step just as slowly.'],
      ['Rushing positions — this is a slow, owned movement.']],
    ['sled-push', 'Sled Push', 'full', 'other', 'time', 'power', ['quads', 'glutes', 'calves'], 'Low body angle, arms locked; drive with short powerful steps.',
      ['Hands on the poles, body at a low angle.', 'Drive with short, powerful steps.', 'Keep the back flat and the effort continuous.'],
      ['Standing too upright and stalling the sled.']],
    ['burpee', 'Burpee', 'full', 'bodyweight', 'bw', 'power', ['cardio'], 'Chest to floor, jump tall at the top; steady rhythm beats sprint-and-die.',
      ['Squat down, hands to the floor, feet jump back.', 'Chest touches the floor; push up and jump the feet in.', 'Jump tall with arms overhead; repeat with rhythm.'],
      ['Sprinting the first five and dying on the rest.']],
    ['med-ball-slam', 'Medicine Ball Slam', 'full', 'other', 'wr', 'power', ['core', 'lats'], 'Full reach overhead, slam through the floor; hinge to pick up, repeat fast.',
      ['Reach the ball fully overhead, up on your toes.', 'Slam it through the floor with your whole trunk.', 'Hinge to collect it and go again.'],
      ['Slamming with just the arms — the trunk throws it.']],
    ['battle-ropes', 'Battle Ropes', 'full', 'other', 'time', 'power', ['shoulders', 'core', 'cardio'], 'Athletic stance; alternating or double waves, big amplitude.',
      ['Athletic stance, slight squat, rope ends in hand.', 'Whip alternating or double waves with big amplitude.', 'Keep breathing — the waves shrink when you hold your breath.'],
      ['Standing tall and letting the waves die halfway down the rope.']],

    /* ---------------- Gym cardio ---------------- */
    ['treadmill-run', 'Treadmill Run', 'cardio', 'cardio', 'time', 'cardio', [], 'Outdoor runs belong in the Run tab — log gym sessions here by duration.',
      ['Set a 1% incline to mimic outdoor effort.', 'Run relaxed: tall posture, quick light steps.'],
      ['Holding the rails.']],
    ['incline-walk', 'Incline Treadmill Walk', 'cardio', 'cardio', 'time', 'cardio', [], '10–15% incline, 5–6 km/h; low-impact engine building.',
      ['Set 10–15% incline at a brisk walking speed.', 'Walk tall without holding on; pump the arms.'],
      ['Hanging off the console — it deletes the incline.']],
    ['bike-erg', 'Indoor Cycling', 'cardio', 'cardio', 'time', 'cardio', [], 'Great zero-impact cross-training on easy or rest days.',
      ['Saddle height: knee slightly bent at the bottom of the stroke.', 'Spin at a comfortable 80–95 rpm for easy days.'],
      ['Grinding a heavy gear at low cadence on recovery days.']],
    ['row-erg', 'Rowing Erg', 'cardio', 'cardio', 'time', 'cardio', ['back', 'legs'], 'Legs → hips → arms; damper 4–6 is plenty.',
      ['Order is legs, then hips, then arms — reverse on the return.', 'Damper at 4–6; long, patient strokes.'],
      ['Yanking with the arms first.']],
    ['elliptical', 'Elliptical', 'cardio', 'cardio', 'time', 'cardio', [], 'Smooth cross-training; keep effort conversational on recovery days.',
      ['Stand tall, push through the whole foot.', 'Use the handles actively for a whole-body rhythm.'],
      ['Slumping over the console.']],
    ['stair-climber', 'Stair Climber', 'cardio', 'cardio', 'time', 'cardio', ['glutes', 'calves'], 'Stand tall, light fingertip balance only.',
      ['Step fully onto each stair, standing tall.', 'Fingertips for balance only.'],
      ['Propping your bodyweight on the rails.']],
    ['swim', 'Swimming', 'cardio', 'cardio', 'time', 'cardio', ['full body'], 'The recovery-day king — zero impact, big aerobic return.',
      ['Long, relaxed strokes; exhale into the water.', 'Mix strokes to keep shoulders happy.'],
      ['Holding your breath between strokes.']],
    ['jump-rope', 'Jump Rope', 'cardio', 'cardio', 'time', 'cardio', ['calves'], 'Soft ankles, low hops; excellent calf and foot conditioning for running.',
      ['Elbows in, wrists spin the rope.', 'Hop low — just enough to clear.'],
      ['Big double-footed leaps that trash the calves.']],
    ['assault-bike', 'Assault Bike', 'cardio', 'cardio', 'time', 'cardio', [], 'Intervals hurt beautifully here; pace the first one.',
      ['Push and pull with arms and legs together.', 'For intervals: hard 20–40 s, easy 60–90 s.'],
      ['Going out at 100% on interval one.']],
    ['hike', 'Hiking', 'cardio', 'cardio', 'time', 'cardio', ['legs'], 'Time on feet with none of the pounding — long-run friendly.',
      ['Shorten your stride on climbs; use the whole foot on descents.'],
      ['Racing the descents on tired legs.']],
  ];

  const GROUPS = [
    ['chest', 'Chest'], ['back', 'Back'], ['shoulders', 'Shoulders'],
    ['biceps', 'Biceps'], ['triceps', 'Triceps'], ['forearms', 'Forearms'],
    ['quads', 'Quads'], ['hamstrings', 'Hamstrings'], ['glutes', 'Glutes'],
    ['calves', 'Calves'], ['core', 'Core'], ['full', 'Full body'], ['cardio', 'Cardio'],
  ];

  const EQUIP = [
    ['barbell', 'Barbell'], ['dumbbell', 'Dumbbell'], ['machine', 'Machine'],
    ['cable', 'Cable'], ['bodyweight', 'Bodyweight'], ['kettlebell', 'Kettlebell'],
    ['other', 'Other'], ['cardio', 'Cardio machine'],
  ];

  const PATTERNS = {
    'hpush': 'Horizontal push', 'vpush': 'Vertical push',
    'hpull': 'Horizontal pull', 'vpull': 'Vertical pull',
    'squat': 'Squat', 'hinge': 'Hip hinge', 'lunge': 'Single-leg',
    'iso-chest': 'Chest isolation', 'iso-side': 'Shoulder raise', 'iso-rear': 'Rear delt / upper back',
    'iso-bi': 'Biceps curl', 'iso-tri': 'Triceps extension',
    'iso-quad': 'Quad isolation', 'iso-ham': 'Hamstring curl', 'iso-glute': 'Hip isolation',
    'calf': 'Calves & shins', 'grip': 'Grip · traps · carries',
    'core-anti': 'Core — stability', 'core-flex': 'Core — flexion',
    'power': 'Power & conditioning', 'cardio': 'Cardio',
  };

  const list = rows.map(([id, name, group, equipment, track, pattern, secondary, cue, how, avoid]) =>
    ({ id, name, group, equipment, track, pattern, secondary, cue, how, avoid, builtin: true }));

  return {
    list,
    GROUPS,
    EQUIP,
    PATTERNS,
    groupName(key) { const g = GROUPS.find(g => g[0] === key); return g ? g[1] : key; },
    equipName(key) { const e = EQUIP.find(e => e[0] === key); return e ? e[1] : key; },
    patternName(key) { return PATTERNS[key] || null; },
  };
})();
